#!/bin/sh
echo "*********************************************************"
echo "                  CrashlogViewer                         "
echo "                Enigma2 plugin/extension                 "
echo "*********************************************************"
echo " Successfully INSTALLED. You should restart Enigma2 now. "
echo "*********************************************************"
exit 0 
